# Generated by Django 4.1.2 on 2022-10-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('allergies', models.CharField(max_length=100)),
                ('insurance', models.CharField(max_length=100)),
            ],
        ),
    ]
