# Generated by Django 4.1.2 on 2022-10-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Procedure Date')),
                ('type', models.CharField(max_length=1)),
                ('location', models.CharField(choices=[('R', 'Root Canal'), ('C', 'Cleaning'), ('F', 'Filling'), ('E', 'Extraction'), ('B', 'BiteWings'), ('P', 'Panoramic')], default='R', max_length=1)),
            ],
        ),
    ]
