# Generated by Django 4.1.2 on 2022-10-24 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_procedures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='procedure Date')),
                ('type', models.CharField(choices=[('R', 'Root Canal'), ('C', 'Cleaning'), ('F', 'Filling'), ('E', 'Extraction'), ('B', 'BiteWings'), ('P', 'Panoramic')], default='R', max_length=1)),
                ('location', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='Procedures',
        ),
    ]
