# Generated by Django 4.1.2 on 2022-10-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_patient_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.CharField(choices=[('F', 'Fissure sealent'), ('T', 'Titanium'), ('L', 'Local Anaesthesia'), ('I', 'Impression materials'), ('L', 'Latex'), ('C', 'Composites')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.CharField(choices=[('D', 'Delta Dental'), ('H', 'Humana'), ('U', 'United Concordia'), ('C', 'CareFirst'), ('C', 'Cigna'), ('M', 'MetLife')], default='D', max_length=1),
        ),
    ]
