# Generated by Django 4.1.2 on 2022-10-25 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_photo_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
