# Generated by Django 4.1.2 on 2023-02-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.CharField(choices=[('F', 'Fissure sealent'), ('T', 'Titanium'), ('L', 'Local Anaesthesia'), ('I', 'Impression materials'), ('L', 'Latex'), ('C', 'Composites'), ('N', 'No Allergies')], default='F', max_length=1),
        ),
    ]
